import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, NavLink, useLocation } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Menu, X, MapPin, Phone, Mail, Clock3, ChevronRight } from 'lucide-react';
import { schedule, statusLabel } from './data/schedule';
import './styles.css';

const images = {
  control: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1500&q=85',
  live: 'https://images.unsplash.com/photo-1598387993281-cecf8b71a8f8?auto=format&fit=crop&w=1200&q=85',
  booth: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=1200&q=85',
  console: 'https://images.unsplash.com/photo-1626379953822-baec19c3accd?auto=format&fit=crop&w=1400&q=85',
  mic: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=85',
  detail: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=1200&q=85'
};
const heroSlides = [images.control, images.live, images.booth, images.console, images.detail];

const nav = [['/', 'HOME'], ['/studio', 'STUDIO'], ['/equipment', 'EQUIPMENT'], ['/schedule', 'SCHEDULE'], ['/access', 'ACCESS'], ['/about', 'ABOUT']];

function Header() {
  const [open, setOpen] = useState(false);
  const location = useLocation();
  return <header className="site-header">
    <Link to="/" className="brand" onClick={() => setOpen(false)}><span className="brand-mark">◌</span><span><b>OAK SOUND STUDIO</b><small>RECORDING / MA STUDIO</small></span></Link>
    <button className="menu-button" onClick={() => setOpen(!open)} aria-label="menu">{open ? <X/> : <Menu/>}</button>
    <nav className={open ? 'main-nav open' : 'main-nav'}>{nav.map(([to, label]) => <NavLink key={label} to={to} className={({isActive}) => isActive || (to==='/' && location.pathname==='/') ? 'active' : ''} onClick={() => setOpen(false)}>{label}</NavLink>)}<Link to="/contact" className="nav-cta" onClick={() => setOpen(false)}>CONTACT <ArrowUpRight size={14}/></Link></nav>
  </header>;
}

function Footer() { return <footer><div className="footer-main"><div><Link to="/" className="brand"><span className="brand-mark">◌</span><span><b>OAK SOUND STUDIO</b><small>RECORDING / MA STUDIO</small></span></Link><p className="footer-address">〒151-0051<br/>東京都渋谷区千駄ヶ谷 1-2-3<br/><br/>03-1234-5678<br/>info@oaksound.studio</p></div><div><p className="eyebrow">SITE MAP</p><div className="footer-links">{nav.slice(1).map(([to,l])=><Link key={l} to={to}>{l}</Link>)}<Link to="/contact">CONTACT</Link></div></div><div><p className="eyebrow">INFORMATION</p><div className="footer-links"><a href="#">利用規約</a><a href="#">プライバシーポリシー</a><a href="#">採用情報</a></div></div></div><div className="footer-bottom"><span>© 2026 OAK SOUND STUDIO</span><span>BUILT FOR THE WORK THAT MATTERS.</span></div></footer> }
function Button({to='/contact', children='お問い合わせ'}) { return <Link to={to} className="button">{children}<ArrowRight size={15}/></Link> }
function PageIntro({label, title, sub}) { return <section className="page-intro"><p className="eyebrow">{label}</p><h1>{title}</h1>{sub && <p className="intro-sub">{sub}</p>}</section> }
function SectionTitle({eyebrow, title, children}) { return <div className="section-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children}</div> }

function Home() { const [heroIndex, setHeroIndex] = useState(0); useEffect(() => { const interval = window.setInterval(() => setHeroIndex((current) => (current + 1) % heroSlides.length), 3000); return () => window.clearInterval(interval); }, []); return <><main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">OAK SOUND STUDIO / TOKYO</p><h1>MAKE SOUND.<br/><em>BRING STORIES.</em></h1><div className="hero-rule"/><p className="jp-lead">音を、物語にする場所。</p><p className="hero-desc">プロフェッショナルのための<br/>レコーディングスタジオ / MAスタジオ。<br/>確かな設備と最適な環境で、作品の魅力を引き出します。</p><div className="hero-actions"><Button to="/studio">スタジオを見る</Button><Button to="/contact">お問い合わせ</Button></div></div><div className="hero-image"><div className="hero-slideshow">{heroSlides.map((src, index) => <img key={src} src={src} className={index === heroIndex ? 'is-active' : ''} alt="OAK SOUND STUDIO"/>)}</div></div><div className="hero-scroll">SCROLL <span/></div></section>
  <section className="section features"><SectionTitle eyebrow="WHY OAK SOUND" title={<>制作の質を支える、<br/><em>3つの約束。</em></>}/><div className="feature-list">{[['01','高品質な設備・環境','プロユースに応える機材と音響設計で、レコーディング・MAのクオリティを支えます。'],['02','柔軟な対応力','収録からMAまで一貫して対応。作品や目的に合わせた最適なプランをご提案します。'],['03','スムーズな予約管理','空き状況の確認からご相談まで、制作の流れを止めない運用を整えています。']].map(([n,t,d])=><div className="feature" key={n}><span className="feature-no">{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight className="feature-arrow" size={18}/></div>)}</div></section>
  <section className="section about-split"><div className="about-photo"><img src={images.live}/><span className="image-caption">LIVE ROOM / 02</span></div><div className="about-copy"><p className="eyebrow">ABOUT STUDIO</p><h2>静けさの中に、<br/><em>精度がある。</em></h2><p>OAK SOUND STUDIOは、音楽・アニメ・ゲーム・映像など、あらゆる作品の「音」を支えるために設計されたレコーディング / MAスタジオです。</p><p>耳を澄ませ、対話し、つくる。制作現場に寄り添う環境と、確かな技術を提供します。</p><Button to="/about">私たちについて</Button></div></section>
  <section className="section rooms"><SectionTitle eyebrow="THE SPACES" title={<>音が生まれる、<em>3つの場所。</em></>} children={<Link className="text-link" to="/studio">VIEW STUDIO <ArrowUpRight size={15}/></Link>}/><div className="room-grid"><Link to="/studio" className="room room-large"><img src={images.live}/><span>01 / CONTROL ROOM</span><strong>Mixing, monitoring, and the final decision.</strong></Link><Link to="/studio" className="room"><img src={images.booth}/><span>02 / LIVE ROOM</span><strong>Natural air for every performance.</strong></Link><Link to="/studio" className="room"><img src={images.detail}/><span>03 / BOOTH</span><strong>Intimate, focused, and quiet.</strong></Link></div></section>
  <section className="section equipment-feature"><div><p className="eyebrow">EQUIPMENT / SELECTED</p><h2>音の輪郭をつくる <em>道具たち。</em></h2><p>ヴィンテージと現行機を組み合わせ、現場で選ばれる音を揃えています。</p><Button to="/equipment">機材リストを見る</Button></div><img src={images.console}/></section>
  <SchedulePreview/><ContactBanner/>
 </main><Footer/></> }

function SchedulePreview() { const days=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]; return <section className="section schedule-preview"><div><p className="eyebrow">SCHEDULE / AUGUST 2026</p><h2>制作の予定を、<br/><em>スムーズに。</em></h2><p>空き状況をご確認いただけます。ご希望の日程が決まりましたら、お気軽にご相談ください。</p><Button to="/schedule">予約状況を見る</Button></div><div className="mini-calendar"><div className="calendar-head"><b>2026.08</b><span>MON — SUN</span></div><div className="calendar-grid">{days.map(d=>{const x=schedule.find(s=>s.date.endsWith(String(d).padStart(2,'0')));return <span key={d} className={x?.status||''}>{d}</span>})}</div><div className="legend"><i className="available"/> Available <i className="contact"/> Contact <i className="booked"/> Booked</div></div></section> }
function ContactBanner(){return <section className="contact-banner" style={{backgroundImage:`url(${images.booth})`}}><div><p className="eyebrow">LET'S MAKE SOMETHING</p><h2>まずは、<em>相談する。</em></h2><p className="contact-banner-note">ご相談・空き状況の確認・お見積もりから、お気軽にどうぞ。</p></div><Button>お問い合わせ</Button></section>}

const rooms=[['CONTROL ROOM', images.control,'42.0㎡','Mixing / MA / Monitoring','正確な判断を支える、フラッグシップコントロールルーム。','PMC / ATC monitor, 32ch console, 5.1ch surround'],['LIVE ROOM A', images.live,'38.5㎡','Recording / Ensemble','木と布の響きを活かした、自然な鳴りのライブルーム。','Variable acoustic panels, piano, drum kit'],['LIVE ROOM B', images.detail,'24.0㎡','Recording / ADR','ナレーションから小編成まで、幅広く対応する収録空間。','Vocal booth access, isolated line'],['BOOTH', images.booth,'6.5㎡','Vocal / Foli','声に集中できる、静音性の高い専用ブース。','Reflection filter, talkback system']];
function Studio(){return <><main><PageIntro label="01 / STUDIO" title={<>音に向き合う、<br/><em>4つの空間。</em></>} sub="Recording, mixing, and MA — each room is designed around the work."/><div className="room-list">{rooms.map((r,i)=><article className="room-detail" key={r[0]}><div className="room-number">0{i+1}</div><img src={r[1]}/><div className="room-detail-copy"><p className="eyebrow">{r[0]}</p><h2>{r[4]}</h2><p>{r[5]}</p><dl><div><dt>AREA</dt><dd>{r[2]}</dd></div><div><dt>USE</dt><dd>{r[3]}</dd></div></dl><Link className="text-link" to="/contact">このスペースを相談する <ArrowUpRight size={15}/></Link></div></article>)}</div><ContactBanner/></main><Footer/></>}

const gear=[['MICROPHONE','Neumann U 87 Ai','Large diaphragm condenser / Vocal, instrument'],['MICROPHONE','Neumann M 49 V','Tube condenser / Vocal, narration'],['PREAMP','Universal Audio 610 MkII','Tube preamp / Warm, dimensional tone'],['PREAMP','Neve 1073 DPX','Class-A preamp / Classic presence'],['COMPRESSOR','Teletronix LA-2A','Optical compressor / Smooth leveling'],['OUTBOARD','Manley VOXBOX','Channel strip / Vocal chain'],['MONITOR','PMC result6','Nearfield monitor / Main control room'],['SOFTWARE','Pro Tools Ultimate','DAW / HDX system, 32 I/O']];
function Equipment(){return <><main><PageIntro label="02 / EQUIPMENT" title={<>選べることが、<br/><em>音を自由にする。</em></>} sub="A considered collection of tools for decisive, repeatable work."/><section className="equipment-page section"><div className="equipment-visual"><img src={images.console}/><p>SELECTED SIGNAL PATH / 2026</p></div><div className="gear-table"><div className="gear-tabs">{['ALL','MICROPHONE','PREAMP','COMPRESSOR','OUTBOARD','MONITOR','SOFTWARE'].map(x=><button key={x}>{x}</button>)}</div>{gear.map(([cat,name,desc])=><div className="gear-row" key={name}><span>{cat}</span><div><b>{name}</b><small>{desc}</small></div><ChevronRight size={15}/></div>)}<Button to="/contact">機材について相談する</Button></div></section></main><Footer/></>}

function Calendar(){const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat']; const nums=Array.from({length:31},(_,i)=>i+1); return <div className="calendar"><div className="calendar-title"><b>August 2026</b><span>← &nbsp; MONTH VIEW &nbsp; →</span></div><div className="calendar-week">{days.map(d=><span key={d}>{d}</span>)}</div><div className="calendar-full-grid">{nums.map(d=>{const x=schedule.find(s=>s.date.endsWith(String(d).padStart(2,'0')));return <div className={x?.status||''} key={d}><small>{d}</small><b>{x ? x.status==='available'?'○':x.status==='contact'?'△':'×':'—'}</b></div>})}</div><div className="calendar-legend"><span><i className="available"/> Available / 空きあり</span><span><i className="contact"/> Contact / 要問い合わせ</span><span><i className="booked"/> Booked / 予約済み</span></div></div>}
function Schedule(){return <><main><PageIntro label="03 / SCHEDULE" title={<>空き状況を見て、<br/><em>次の音へ。</em></>} sub="Availability is a starting point. Tell us what you are making and we will find the right setup."/><section className="section schedule-page"><Calendar/><aside><p className="eyebrow">HOW TO BOOK</p><h2>ご利用までの<br/><em>3ステップ。</em></h2>{[['01','日程を確認'],['02','内容を相談'],['03','プランを決定']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><ArrowRight size={15}/></div>)}<Button>空き状況を問い合わせる</Button></aside></section></main><Footer/></>}

function Access(){return <><main><PageIntro label="04 / ACCESS" title={<>制作チームが<br/><em>集まりやすい場所。</em></>} sub="千駄ヶ谷駅から徒歩6分。搬入・長時間の制作にも配慮した立地です。"/><section className="section access-page"><div className="map-placeholder"><MapPin size={28}/><span>OAK SOUND STUDIO<br/><small>MAP AREA</small></span></div><div className="access-info"><div className="info-block"><p className="eyebrow">ADDRESS</p><p>〒151-0051<br/>東京都渋谷区千駄ヶ谷 1-2-3<br/>OAK千駄ヶ谷ビル B1F</p></div><div className="info-block"><p className="eyebrow">TRAIN</p><p>JR総武線「千駄ヶ谷駅」徒歩6分<br/>都営大江戸線「国立競技場駅」徒歩7分</p></div><div className="info-block"><p className="eyebrow">CAR / DELIVERY</p><p>建物前に一時停車スペースあり。大型機材の搬入は事前にご相談ください。</p></div><Button>アクセスについて相談</Button></div></section></main><Footer/></>}

function About(){return <><main><PageIntro label="05 / ABOUT" title={<>音の先にある、<br/><em>物語のために。</em></>} sub="We make room for focus, conversation, and the details that make a work last."/><section className="section about-page"><img src={images.detail}/><div className="about-manifesto"><p className="eyebrow">OUR APPROACH</p><h2>つくる人のそばで、<br/><em>考え続ける。</em></h2><p>良い音は、良い機材だけでは生まれません。作品の意図を理解し、現場の会話に耳を澄ませ、技術で選択肢を増やすこと。</p><p>OAK SOUND STUDIOは、音響制作会社、映像・ゲーム・アニメーションの制作チームとともに、作品が届く最後の一音まで向き合います。</p></div></section><section className="section company"><p className="eyebrow">OPERATING COMPANY</p><div><h2>OAK SOUND STUDIO</h2><p>スタジオ運営 / 音響制作サポート</p></div><dl><div><dt>ESTABLISHED</dt><dd>2026</dd></div><div><dt>LOCATION</dt><dd>Tokyo, Japan</dd></div><div><dt>CONTACT</dt><dd>info@oaksound.studio</dd></div></dl></section><ContactBanner/></main><Footer/></>}

function Contact(){return <><main><PageIntro label="06 / CONTACT" title={<>制作の話を、<br/><em>聞かせてください。</em></>} sub="ご相談・空き状況の確認・お見積もりなど、お気軽にお問い合わせください。"/><section className="section contact-page"><div className="contact-note"><p className="eyebrow">GET IN TOUCH</p><h2>まずは概要だけでも<br/><em>大丈夫です。</em></h2><p>通常2営業日以内に担当者よりご返信します。お急ぎの場合はお電話でも承ります。</p><div className="contact-details"><span><Mail size={16}/> info@oaksound.studio</span><span><Phone size={16}/> 03-1234-5678</span><span><Clock3 size={16}/> 平日 10:00 — 19:00</span></div></div><form onSubmit={e=>e.preventDefault()}><label>会社名 <small>COMPANY</small><input placeholder="株式会社〇〇"/></label><label>氏名 <small>NAME</small><input placeholder="山田 太郎"/></label><label>メールアドレス <small>EMAIL</small><input type="email" placeholder="name@company.jp"/></label><label>電話番号 <small>PHONE</small><input placeholder="03-1234-5678"/></label><label>利用希望日 <small>DATE</small><input placeholder="2026年  月  日"/></label><label>利用用途 <small>PROJECT TYPE</small><select defaultValue=""><option value="" disabled>選択してください</option><option>レコーディング</option><option>MA / ナレーション</option><option>ミックス / マスタリング</option><option>その他</option></select></label><label>お問い合わせ内容 <small>MESSAGE</small><textarea rows="5" placeholder="ご相談内容をご記入ください"/></label><button className="button" type="submit">送信内容を確認する <ArrowRight size={15}/></button></form></section></main><Footer/></>}

function LoadingScreen({visible}) { return <div className={visible ? 'loading-screen is-visible' : 'loading-screen'} aria-hidden={!visible}><div className="loader-inner"><div className="brand loader-brand"><span className="brand-mark loader-mark">◌</span><span><b>OAK SOUND STUDIO</b><small>RECORDING / MA STUDIO</small></span></div><span className="loader-line"/></div></div> }
function PageTransition() { const location = useLocation(); useEffect(() => { window.scrollTo({ top: 0, behavior: 'instant' }); const targets = [...document.querySelectorAll('.page-transition .section, .page-transition .page-intro, .page-transition .room-detail, .page-transition .contact-banner')]; targets.forEach((target) => target.classList.add('scroll-reveal')); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: 0.12, rootMargin: '0px 0px -8% 0px' }); targets.forEach((target) => observer.observe(target)); return () => observer.disconnect(); }, [location.pathname]); return <div className="page-transition" key={location.pathname}><Routes><Route path="/" element={<Home/>}/><Route path="/studio" element={<Studio/>}/><Route path="/equipment" element={<Equipment/>}/><Route path="/schedule" element={<Schedule/>}/><Route path="/access" element={<Access/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/></Routes></div> }
function App(){ const [loading, setLoading] = useState(true); useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 1050); return () => window.clearTimeout(timer) }, []); return <><LoadingScreen visible={loading}/><Header/><PageTransition/></> }
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
